server:
  port: 8080

spring:
  application:
    name: attendance-backend

  datasource:
    # H2 Database (dla testów)
    url: jdbc:h2:mem:attendance_db
    driverClassName: org.h2.Driver
    username: sa
    password: password

    # MySQL (odkomentuj jeśli używasz MySQL)
    # url: jdbc:mysql://localhost:3306/attendance_db?useSSL=false&serverTimezone=UTC
    # username: attendance_user
    # password: attendance_password
    # driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create-drop # create-drop dla testów, update dla produkcji
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect # Dla H2
        # dialect: org.hibernate.dialect.MySQL8Dialect # Dla MySQL

  h2:
    console:
      enabled: true # http://localhost:8080/h2-console
      path: /h2-console

  jackson:
    time-zone: Europe/Warsaw
    date-format: yyyy-MM-dd'T'HH:mm:ss

logging:
  level:
    com.attendance.backend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG