server:
  port: 8080

spring:
  application:
    name: attendance-backend

  datasource:
    url: jdbc:mysql://localhost:3306/attendance_db?useSSL=false&serverTimezone=Europe/Warsaw&allowPublicKeyRetrieval=true
    username: attendance_user
    password: attendance_password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    format-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    defer-datasource-initialization: false
    open-in-view: true

  sql:
    init:
      mode: never

  jackson:
    time-zone: Europe/Warsaw
    date-format: yyyy-MM-dd'T'HH:mm:ss
    serialization:
      fail-on-empty-beans: false

logging:
  level:
    com.attendance.backend: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG